FIND_PATH(LPSOLVE_INCLUDE_DIR lp_lib.h
  PATH_SUFFIXES lpsolve
  PATHS include
)

FIND_LIBRARY(LPSOLVE_LIBRARY
  NAMES lpsolve55
  PATHS ENV LIB
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LPSOLVE DEFAULT_MSG
  LPSOLVE_INCLUDE_DIR
  LPSOLVE_LIBRARY
)

IF(LPSOLVE_FOUND)
  SET(LPSOLVE_INCLUDE_DIRS ${LPSOLVE_INCLUDE_DIR})
  SET(LPSOLVE_LIBRARIES "${LPSOLVE_LIBRARY}")
ENDIF(LPSOLVE_FOUND)

MARK_AS_ADVANCED(
  LPSOLVE_INCLUDE_DIR
  LPSOLVE_LIBRARY
)
